AWSTemplateFormatVersion: 2010-09-09
Description: Provides a demo environment with a Wazuh cluster of two nodes, Elasticsearch cluster of three nodes with opendistro.
Mappings:
  RegionMap:
    us-east-1:
      HVM64: ami-0c6b1d09930fac512
      HVMCENTOS7: ami-02eac2c0129f6376b
      HVMUBUNTU64: ami-024a64a6685d05041
      HVMREDHAT7: ami-6871a115
      HVMDEBIAN: ami-0357081a1383dc76b
      HVMWINDOWS: ami-0a9ca0496f746e6e0

    us-east-2:
      HVM64: ami-0ebbf2179e615c338
      HVMCENTOS7: ami-0f2b4fc905b0bd1f1
      HVMUBUNTU64: ami-097ebb39620d8d54b
      HVMREDHAT7: ami-03291866
      HVMDEBIAN: ami-09c10a66337c79669
      HVMWINDOWS: ami-0087a83ed4a60d1e9

    us-west-1:
      HVM64: ami-015954d5e5548d13b
      HVMUBUNTU64: ami-040dfc3ebf1bfc4f6
      HVMCENTOS7: ami-074e2d6769f445be5
      HVMREDHAT7: ami-18726478
      HVMDEBIAN: ami-0adbaf2e0ce044437
      HVMWINDOWS: ami-0069635df219ce9e5
    us-west-2:
      HVM64: ami-0cb72367e98845d43
      HVMUBUNTU64: ami-0196ce5c34425a906
      HVMCENTOS7: ami-01ed306a12b7d1c96
      HVMREDHAT7: ami-28e07e50
      HVMDEBIAN: ami-05a3ef6744aa96514
      HVMWINDOWS: ami-04ad37d2932b886c0
    ca-central-1:
      HVM64: ami-08a9b721ecc5b0a53
      HVMUBUNTU64: ami-0380eb76ff3ad603f
      HVMCENTOS7: ami-033e6106180a626d0
      HVMREDHAT7: ami-49f0762d
      HVMDEBIAN: ami-04413a263a7d94982
      HVMWINDOWS: ami-020e569ea1f3a4e1c
    eu-west-1:
      HVM64: ami-030dbca661d402413
      HVMUBUNTU64: ami-0b2a4d260c54e8d3d
      HVMCENTOS7: ami-0ff760d16d9497662
      HVMREDHAT7: ami-7c491f05
      HVMDEBIAN: ami-0968f6a31fc6cffc0
      HVMWINDOWS: ami-03838ccd5cfb84782
    eu-west-2:
      HVM64: ami-0009a33f033d8b7b6
      HVMUBUNTU64: ami-09dd110e91f421069
      HVMCENTOS7: ami-0eab3a90fc693af19
      HVMREDHAT7: ami-7c1bfd1b
      HVMDEBIAN: ami-0faa9c9b5399088fd
      HVMWINDOWS: ami-0ebf422d2a92724ec
    eu-west-3:
      HVM64: ami-0ebb3a801d5fb8b9b
      HVMUBUNTU64: ami-00e557eb4a269bf1c
      HVMCENTOS7: ami-0e1ab783dc9489f34
      HVMREDHAT7: ami-5026902d
      HVMDEBIAN: ami-0cd23820af84edc85
      HVMWINDOWS: ami-022cfeccb4b72d6b8
    ap-northeast-1:
      HVM64: ami-00d101850e971728d
      HVMUBUNTU64: ami-0b5a5c971fc30e5d1
      HVMCENTOS7: ami-045f38c93733dd48d
      HVMREDHAT7: ami-6b0d5f0d
      HVMDEBIAN: ami-09fbcd30452841cb9
      HVMWINDOWS: ami-02192102f14f0a10a
    ap-northeast-2:
      HVM64: ami-08ab3f7e72215fe91
      HVMUBUNTU64: ami-06af4ace0697354bf
      HVMCENTOS7: ami-06cf2a72dadf92410
      HVMREDHAT7: ami-3eee4150
      HVMDEBIAN: ami-08363ccce96df1fff
      HVMWINDOWS: ami-0708a3b845edea89c
    ap-southeast-1:
      HVM64: ami-0b5a47f8865280111
      HVMUBUNTU64: ami-0355471dc9f264631
      HVMCENTOS7: ami-0b4dd9d65556cac22
      HVMREDHAT7: ami-76144b0a
      HVMDEBIAN: ami-0555b1a5444087dd4
      HVMWINDOWS: ami-0afce41e503676765
    ap-southeast-2:
      HVM64: ami-0fb7513bcdc525c3b
      HVMUBUNTU64: ami-0065540df76a93885
      HVMCENTOS7: ami-08bd00d7713a39e7d
      HVMREDHAT7: ami-67589505
      HVMDEBIAN: ami-029c54f988446691a
      HVMWINDOWS: ami-0628ef1f10e34307d
    ap-south-1:
      HVM64: ami-00e782930f1c3dbc7
      HVMUBUNTU64: ami-076b389b9989430c2
      HVMCENTOS7: ami-02e60be79e78fef21
      HVMREDHAT7: ami-5b673c34
      HVMDEBIAN: ami-0dc98cbb0d0e49162
      HVMWINDOWS: ami-0e719217acb64308e
    sa-east-1:
      HVM64: ami-058141e091292ecf0
      HVMUBUNTU64: ami-009e4c831385f8901
      HVMCENTOS7: ami-0b8d86d4bf91850af
      HVMREDHAT7: ami-b0b7e3dc
      HVMDEBIAN: ami-030580e61468e54bd
      HVMWINDOWS: ami-07df12f3c5005cd1f
  SubnetConfig:
    WazuhVpc:
      CIDR: 10.0.0.0/16
    SubnetElasticsearch:
      CIDR: 10.0.2.0/24

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:

      -
        Label:
          default: "AWS environment"
        Parameters:
          - AvailabilityZone
          - KeyPairName
      - 
        Label:
          default: "Version and instance types"
        Parameters:
          - KibanaInstanceType


Parameters:

  # AWS environment 
  AvailabilityZone:
    Description: Select an availability zone for the VPC
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  KeyPairName:
    Description: Existing EC2 key pair for SSH access
    Type: 'AWS::EC2::KeyPair::KeyName'

  KibanaInstanceType:
    AllowedValues:
      - t2.medium
      - t2.large
      - m5.large
      - m5d.large
      - m5.xlarge
      - m5.2xlarge
      - r5.large

    ConstraintDescription: Must contain valid instance type
    Default: t2.medium
    Description: Type of EC2 instance for Kibana instance
    Type: String

  # Kibana configuration
  KibanaPort:
    Default: '5601'
    Description: Port for Kibana WUI
    Type: String

Resources:

  # Network resources
  WazuhVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !FindInMap
        - SubnetConfig
        - WazuhVpc
        - CIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: service_name
          Value: Opendistro-SAML-test

  SubnetElasticsearch:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref WazuhVpc
        CidrBlock: !FindInMap
          - SubnetConfig
          - SubnetElasticsearch
          - CIDR
        Tags:
          - Key: service_name
            Value: Opendistro-SAML-test

  # Internet access and routing
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: service_name
          Value: Opendistro-SAML-test
  GatewayToInternet:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref WazuhVpc
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref WazuhVpc
      Tags:
        - Key: service_name
          Value: Opendistro-SAML-test
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetElasticPublicRouteTable:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetElasticsearch
      RouteTableId: !Ref PublicRouteTable

  KibanaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Kibana security group
      VpcId: !Ref WazuhVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref KibanaPort
          ToPort: !Ref KibanaPort
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9200
          ToPort: 9400
          CidrIp: !FindInMap
            - SubnetConfig
            - WazuhVpc
            - CIDR
      Tags:
        - Key: service_name
          Value: Opendistro-SAML-test
 
  # IAM role and profile
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-GetCloudformation'
          PolicyDocument:
            Statement:
              - Action:
                  - 'cloudformation:DescribeStack*'
                  - 'cloudformation:DescribeStackResource*'
                  - 'cloudformation:List*'
                Resource: '*'
                Effect: Allow
        - PolicyName: !Sub '${AWS::StackName}-DescribeInstances'
          PolicyDocument:
            Statement:
              - Action:
                  - 'ec2:DescribeInstances'
                Resource: '*'
                Effect: Allow
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref InstanceRole

  # Kibana instance
  KibanaInstance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          KibanaInstallationSet:
            - KibanaFiles
            - KibanaInstall
        KibanaFiles:
          files:
            /tmp/wazuh_cf_opendistro.sh:
              source: !Sub >-
                https://raw.githubusercontent.com/wazuh/wazuh-cloudformation/opendistro-simple-host/opendistro/wazuh_cf_opendistro.sh
              mode: '000700'
              owner: root
              group: root
        KibanaInstall:
          commands:
            01_RunInstallationScript:
              command: /tmp/wazuh_cf_opendistro.sh
    Properties:
      ImageId: !FindInMap
        - "RegionMap"
        - Ref: "AWS::Region"
        - HVM64
      InstanceType: !Ref KibanaInstanceType
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "KibanaSecurityGroup"
          SubnetId: 
            Ref: "SubnetElastic"
      Tags:
        - Key: service_name
          Value: Opendistro-SAML-test
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource KibanaInstance --configsets KibanaInstallationSet --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Kibana --region ${AWS::Region}
    DependsOn: GatewayToInternet